openapi: '3.1.0'
info:
  title: MiToolAPIService
  version: 1.0.0
servers:
  - url: https://api-takumi-record.mihoyo.com
    description: Mihoyo service deployment.
  - url: https://example-takumi.mihoyo.com
    description: Example service deployment.
paths:
  /game_record/card/api/getGameRecordCard:
    get:
      operationId: mihoyoUID
      parameters:
        - name: uid
          required: true
          in: query
          description: The uid used in the returned Mihoyo.
          schema:
            type: string
      responses:
        '200':
          description: A success response with a greeting.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameRecord'
components:
  schemas:
    GameRecord:
      type: object
      properties:
        message:
          type: string
      required:
        - message
